# Generated by Django 6.0.5 on 2026-05-26 08:09

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='smtp_config', serialize=False, to='organizations.organization')),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', core.fields.EncryptedTextField(blank=True, default='')),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
