# Generated by Django 6.0.5 on 2026-05-26 08:04

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='organizations.organization')),
                ('logo_url', models.TextField(blank=True, default='')),
                ('brand_colors', models.JSONField(blank=True, default=dict)),
                ('plan', models.CharField(choices=[('internal', 'Internal'), ('saas', 'SaaS')], default='internal', max_length=20)),
                ('openai_api_key', core.fields.EncryptedTextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Organization Profile',
                'verbose_name_plural': 'Organization Profiles',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUserProfile',
            fields=[
                ('org_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='organizations.organizationuser')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=20)),
                ('avatar_url', models.TextField(blank=True, default='')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organization User Profile',
                'verbose_name_plural': 'Organization User Profiles',
            },
        ),
    ]
