# Generated by Django 6.0.5 on 2026-05-26 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_features', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('organizations', '0006_alter_organization_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='aijob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aijob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='organizations.organization'),
        ),
    ]
