# Generated by Django 6.0.5 on 2026-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aijob',
            name='job_type',
            field=models.CharField(choices=[('subject_lines', 'Subject Lines'), ('copy_optimize', 'Copy Optimize'), ('spam_check', 'Spam Check'), ('cta_suggest', 'CTA Suggest'), ('email_build', 'Email Build')], max_length=30),
        ),
    ]
