# Generated by Django 6.0.5 on 2026-05-26 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('promo', 'Promotion'), ('newsletter', 'Newsletter'), ('announcement', 'Announcement'), ('webinar', 'Webinar'), ('onboarding', 'Onboarding'), ('outreach', 'Outreach')], default='promo', max_length=50)),
                ('thumbnail_url', models.TextField(blank=True, default='')),
                ('gjs_components', models.JSONField(blank=True, default=dict)),
                ('gjs_styles', models.JSONField(blank=True, default=dict)),
                ('mjml_source', models.TextField(blank=True, default='')),
                ('html_output', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
